spring:
  thymeleaf:
    cache: false                                    # 开发时禁用缓存
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/